- name: 🧾 Get AWS ECR login password
  shell: >
    aws ecr get-login-password --region {{ aws_region }} |
    docker login --username AWS --password-stdin {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com
  register: ecr_login
  changed_when: false

- name: ✅ Print ECR login result
  debug:
    var: ecr_login.stdout

- name: 📤 Push Docker image to AWS ECR
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    source: local
    push: true
  register: push_to_ecr

- name: ✅ Print push result
  debug:
    var: push_to_ecr
