- name: 🚀 Run or Update Docker container
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
    pull: yes           # Pull latest image from ECR
    recreate: yes       # Recreate container if image tag changed
    state: started
    ports: "{{ docker_ports }}"
    restart_policy: always
  register: run_result

- name: 🪵 Debug Run Result
  debug:
    var: run_result
